name: CI CD build & test

on:
  push:
    branches:
      - main

env:
  IMAGE:  ghcr.io/$GITHUB_REPOSITORY/py-solis-s3-logger

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Log in to GitHub Packages
        run: "echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./Dockerfile "."
      - name: Push image
        run: |
          docker push ${{ env.IMAGE }}:latest

#   test:
#     name: Test Docker Image
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout master
#         uses: actions/checkout@v1
#       - name: Log in to GitHub Packages
#         run: "echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Pull image
#         run: |
#           docker pull ${{ env.IMAGE }}:latest || true
#       - name: Build image
#         run: |
#           docker build \
#             --cache-from ${{ env.IMAGE }}:latest \
#             --tag ${{ env.IMAGE }}:latest \
#             --file ./Dockerfile \
#             "./"
#       - name: Run container
#         run: |
#           docker run \
#             -d \
#             --name alarm-monitor-app \
#             -e PORT=8000 \
#             -e ENVIRONMENT=dev \
#             -p 8000:8000 \
#             ${{ env.IMAGE }}:latest
#        TODO hatch
#       - name: Install requirements
#         run: docker exec --user app py-solis-s3-logger pip --no-cache-dir install pytest==6.2.5 requests==2.26.0
#       - name: Pytest
#         run: docker exec --user app py-solis-s3-logger python -m pytest .
